### ISSUE TITLE
Error installing jfrog_siem plugin

### ISSUE THREAD

**Issue by jellard1** [jfrog/log-analytics-splunk#41]
I am running fluentd in the official image from dockerhub. I am using the fluent.conf.xray from this repo (with required modifications) and I get error starting fluentd:
`[error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Unknown input plugin 'jfrog_siem'. Run 'gem search -rd fluent-plugin to find plugins`

Ok, just run the fluen-gem install command, blam!:
```ruby
root@13eb89abbb26:/# fluent-gem install fluent-plugin-jfrog-siem
Fetching http-accept-1.7.0.gem
Fetching unf-0.1.4.gem
Fetching domain_name-0.5.20190701.gem
Fetching unf_ext-0.0.8.gem
Fetching mime-types-3.4.1.gem
Fetching netrc-0.11.0.gem
Fetching http-cookie-1.0.4.gem
Fetching mime-types-data-3.2022.0105.gem
Fetching fluent-plugin-jfrog-siem-2.0.1.gem
Fetching rest-client-2.1.0.gem
Fetching concurrent-ruby-edge-0.6.0.gem
Successfully installed http-accept-1.7.0
Building native extensions. This could take a while...
ERROR:  Error installing fluent-plugin-jfrog-siem:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/unf_ext-0.0.8/ext/unf_ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r ./siteconf20220110-11-1sis4ah.rb extconf.rb
checking for -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-static-libstdc++
        --without-static-libstdc++
        --with-stdc++lib
        --without-stdc++lib
/usr/local/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:552:in `try_link0'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:789:in `try_func'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/2.6.0/unf_ext-0.0.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/unf_ext-0.0.8 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.6.0/unf_ext-0.0.8/gem_make.out
```

I'm stuck here. Other required plugins weren't any issue: `fluent-plguin-splunk-enterprise` `fluent-plugin-splunk-hec`

**Comment by benharosh** [comment]
Old issue. Can't repro. Closing
